name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Azure Static Web Apps
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # created by Azure when you connect GitHub; if Azure uses a different secret name, update this
          repo_token: ${{ secrets.GITHUB_TOKEN }} # used for PR comments
          action: "upload"
          app_location: "/" # App source code path
          api_location: "" # No API
          app_artifact_location: "/" # Built app content directory (root for this static site)
